"""initial schema

Revision ID: aea14cec7369
Revises: 
Create Date: 2026-08-11 21:56:26.273267
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aea14cec7369'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_hash'), 'audit_log', ['hash'], unique=True)
    op.create_index(op.f('ix_audit_log_object_id'), 'audit_log', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_log_object_type'), 'audit_log', ['object_type'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('workpiece_no', sa.String(length=64), nullable=True),
    sa.Column('weld_no', sa.String(length=64), nullable=True),
    sa.Column('pixel_spacing_mm', sa.Float(), nullable=True),
    sa.Column('base_metal_thickness_mm', sa.Float(), nullable=True),
    sa.Column('iqi_pass', sa.Boolean(), nullable=True),
    sa.Column('iqi_detail', sa.JSON(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('density_ok', sa.Boolean(), nullable=True),
    sa.Column('pseudo_defect_pass', sa.Boolean(), nullable=True),
    sa.Column('pseudo_defect_notes', sa.JSON(), nullable=True),
    sa.Column('quality_pass', sa.Boolean(), nullable=True),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('evaluable', sa.Boolean(), nullable=False),
    sa.Column('preprocess_params', sa.JSON(), nullable=False),
    sa.Column('joint_level', sa.String(length=8), nullable=True),
    sa.Column('need_review', sa.Boolean(), nullable=False),
    sa.Column('standard_id', sa.String(length=64), nullable=True),
    sa.Column('standard_version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_created_at'), 'images', ['created_at'], unique=False)
    op.create_index(op.f('ix_images_joint_level'), 'images', ['joint_level'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('bbox_px', sa.JSON(), nullable=True),
    sa.Column('shape', sa.String(length=16), nullable=True),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('area_mm2', sa.Float(), nullable=True),
    sa.Column('perimeter_mm', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('joint_level', sa.String(length=8), nullable=True),
    sa.Column('need_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('standard_id', sa.String(length=64), nullable=True),
    sa.Column('standard_version', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_image_id'), 'defects', ['image_id'], unique=False)
    op.create_index(op.f('ix_defects_joint_level'), 'defects', ['joint_level'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('joint_level', sa.String(length=8), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=False),
    sa.Column('standard_ref', sa.String(length=128), nullable=True),
    sa.Column('signer', sa.String(length=64), nullable=True),
    sa.Column('basis', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_image_id'), 'reports', ['image_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('overall_level', sa.String(length=8), nullable=True),
    sa.Column('kappa', sa.Float(), nullable=False),
    sa.Column('consensus', sa.Boolean(), nullable=False),
    sa.Column('needs_arbitration', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_image_id'), 'reviews', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_image_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reports_image_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_defects_joint_level'), table_name='defects')
    op.drop_index(op.f('ix_defects_image_id'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_images_joint_level'), table_name='images')
    op.drop_index(op.f('ix_images_created_at'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_audit_log_object_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_object_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_hash'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
